import { describe, it, expect } from 'vitest'
import path from 'node:path'
import { parseContent, parseLine, parseSession, stripSystemXml } from '../src/main/parser'

const FIXTURES = path.join(__dirname, 'fixtures')

describe('stripSystemXml', () => {
  // --- strip（完全移除標籤+內容）---

  it('removes <local-command-caveat> entirely', () => {
    const input = '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>'
    expect(stripSystemXml(input)).toBe('')
  })

  it('removes <task-notification> with nested tags', () => {
    const input = `<task-notification>
<task-id>bd93ty0eu</task-id>
<tool-use-id>toolu_016ZHSw5mPuUjNTWcv4RQbiy</tool-use-id>
<output-file>/private/tmp/claude-501/tasks/bd93ty0eu.output</output-file>
<status>completed</status>
<summary>Background command completed (exit code 0)</summary>
</task-notification>`
    expect(stripSystemXml(input)).toBe('')
  })

  it('removes <ide_opened_file> entirely', () => {
    const input = '<ide_opened_file>The user opened the file /Users/foo/bar.ts in the IDE. This may or may not be related to the current task.</ide_opened_file>'
    expect(stripSystemXml(input)).toBe('')
  })

  it('removes <system-reminder> entirely', () => {
    const input = '<system-reminder>Some system reminder text here.</system-reminder>'
    expect(stripSystemXml(input)).toBe('')
  })

  // --- unwrap（移除標籤，保留內容）---

  it('unwraps <command-name> keeping inner text', () => {
    const input = '<command-name>/gogo</command-name>'
    expect(stripSystemXml(input)).toBe('/gogo')
  })

  it('unwraps <command-message> keeping inner text', () => {
    const input = '<command-message>gogo</command-message>'
    expect(stripSystemXml(input)).toBe('gogo')
  })

  it('unwraps <command-args> keeping inner text', () => {
    const input = '<command-args>--verbose</command-args>'
    expect(stripSystemXml(input)).toBe('--verbose')
  })

  it('unwraps <local-command-stdout> keeping output text', () => {
    const input = '<local-command-stdout>Compacted </local-command-stdout>'
    expect(stripSystemXml(input)).toBe('Compacted')
  })

  // --- 混合場景 ---

  it('handles mixed system XML + user text', () => {
    const input = '<local-command-caveat>Caveat: DO NOT respond.</local-command-caveat>\nHello, please help me'
    expect(stripSystemXml(input)).toBe('Hello, please help me')
  })

  it('handles multiple system tags in one string', () => {
    const input = '<command-message>save-t</command-message>\n<command-name>/save-t</command-name>'
    expect(stripSystemXml(input)).toBe('save-t\n/save-t')
  })

  // --- 安全邊界 ---

  it('does NOT touch unknown XML tags (whitelist only)', () => {
    const input = '<custom-tag>user content</custom-tag>'
    expect(stripSystemXml(input)).toBe('<custom-tag>user content</custom-tag>')
  })

  it('does NOT touch HTML tags', () => {
    const input = '<div>some html</div>'
    expect(stripSystemXml(input)).toBe('<div>some html</div>')
  })

  it('returns empty string when only system XML remains', () => {
    const input = '<ide_opened_file>The user opened foo.ts in the IDE.</ide_opened_file>'
    expect(stripSystemXml(input)).toBe('')
  })

  it('trims surrounding whitespace after stripping', () => {
    const input = '  <local-command-caveat>Caveat text.</local-command-caveat>  \n  '
    expect(stripSystemXml(input)).toBe('')
  })

  it('handles empty string input', () => {
    expect(stripSystemXml('')).toBe('')
  })

  it('passes through plain text unchanged', () => {
    expect(stripSystemXml('Hello world')).toBe('Hello world')
  })
})

describe('parseContent', () => {
  it('string content → contentText directly', () => {
    const result = parseContent('Hello world')
    expect(result.contentText).toBe('Hello world')
    expect(result.hasToolUse).toBe(false)
    expect(result.hasToolResult).toBe(false)
    expect(result.toolNames).toEqual([])
  })

  it('null content → contentText null', () => {
    const result = parseContent(null)
    expect(result.contentText).toBeNull()
  })

  it('array with text blocks → concatenated with newline', () => {
    const content = [
      { type: 'text', text: 'Line 1' },
      { type: 'text', text: 'Line 2' },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('Line 1\nLine 2')
  })

  it('array with tool_use → marks flag and records name', () => {
    const content = [
      { type: 'text', text: 'Let me read it.' },
      { type: 'tool_use', id: 'toolu_001', name: 'Read', input: {} },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('Let me read it.')
    expect(result.hasToolUse).toBe(true)
    expect(result.toolNames).toEqual(['Read'])
  })

  it('array with tool_result → marks flag', () => {
    const content = [
      { type: 'tool_result', tool_use_id: 'toolu_001', content: 'file data' },
    ]
    const result = parseContent(content)
    expect(result.hasToolResult).toBe(true)
    expect(result.contentText).toBeNull()
  })

  it('array with thinking → skipped, not in contentText', () => {
    const content = [
      { type: 'thinking', thinking: 'Let me think...' },
      { type: 'text', text: 'Here is the answer.' },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('Here is the answer.')
  })

  it('multiple tool_use → records all names', () => {
    const content = [
      { type: 'tool_use', id: 'toolu_001', name: 'Read', input: {} },
      { type: 'tool_use', id: 'toolu_002', name: 'Bash', input: {} },
    ]
    const result = parseContent(content)
    expect(result.toolNames).toEqual(['Read', 'Bash'])
  })

  it('strips system XML from string content', () => {
    const content = '<local-command-caveat>Caveat text.</local-command-caveat>'
    const result = parseContent(content)
    expect(result.contentText).toBeNull()
  })

  it('strips system XML from array text blocks', () => {
    const content = [
      { type: 'text', text: '<ide_opened_file>User opened foo.ts.</ide_opened_file>' },
      { type: 'text', text: 'Real user message here' },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('Real user message here')
  })

  it('unwraps command tags in array text blocks', () => {
    const content = [
      { type: 'text', text: '<command-message>gogo</command-message>\n<command-name>/gogo</command-name>' },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('gogo\n/gogo')
  })
})

describe('parseLine', () => {
  it('user message with string content', () => {
    const line = JSON.stringify({
      type: 'user',
      uuid: 'u1',
      parentUuid: null,
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 'sess-001',
      message: { role: 'user', content: 'Hello' },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('user')
    expect(result!.role).toBe('user')
    expect(result!.contentText).toBe('Hello')
    expect(result!.uuid).toBe('u1')
    expect(result!.timestamp).toBe('2024-06-01T10:00:00.000Z')
  })

  it('assistant message with tool_use', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a1',
      parentUuid: 'u1',
      timestamp: '2024-06-01T10:00:01.000Z',
      sessionId: 'sess-001',
      message: {
        role: 'assistant',
        content: [
          { type: 'text', text: 'Reading file.' },
          { type: 'tool_use', id: 'toolu_001', name: 'Read', input: {} },
        ],
      },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.role).toBe('assistant')
    expect(result!.contentText).toBe('Reading file.')
    expect(result!.hasToolUse).toBe(true)
    expect(result!.toolNames).toEqual(['Read'])
  })

  it('malformed JSON → returns null', () => {
    expect(parseLine('NOT VALID JSON')).toBeNull()
    expect(parseLine('{{{broken')).toBeNull()
  })

  it('empty line → returns null', () => {
    expect(parseLine('')).toBeNull()
    expect(parseLine('  ')).toBeNull()
  })

  it('unknown type → still returns ParsedLine', () => {
    const line = JSON.stringify({ type: 'file-history-snapshot', sessionId: 's1' })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('file-history-snapshot')
    expect(result!.contentText).toBeNull()
  })

  it('queue-operation with content → extracts prompt text', () => {
    const line = JSON.stringify({
      type: 'queue-operation',
      operation: 'enqueue',
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 's1',
      content: 'Help me debug this',
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('queue-operation')
    expect(result!.role).toBeNull()
    expect(result!.contentText).toBe('Help me debug this')
  })

  it('queue-operation without content → contentText null', () => {
    const line = JSON.stringify({
      type: 'queue-operation',
      operation: 'dequeue',
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 's1',
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.contentText).toBeNull()
  })

  it('extracts requestId from top-level field', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a1',
      requestId: 'req_011CZVkxXRnVB3AAiJXkgBUm',
      timestamp: '2024-06-01T10:00:01.000Z',
      sessionId: 'sess-001',
      message: { role: 'assistant', content: [{ type: 'text', text: 'Hello' }] },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.requestId).toBe('req_011CZVkxXRnVB3AAiJXkgBUm')
  })

  it('requestId is null when field is missing', () => {
    const line = JSON.stringify({
      type: 'user',
      uuid: 'u1',
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 's1',
      message: { role: 'user', content: 'Hello' },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.requestId).toBeNull()
  })

  it('requestId is null when field is not a string', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a1',
      requestId: 12345,
      timestamp: '2024-06-01T10:00:01.000Z',
      sessionId: 'sess-001',
      message: { role: 'assistant', content: [{ type: 'text', text: 'Hi' }] },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.requestId).toBeNull()
  })
})

describe('parseSession', () => {
  it('sample.jsonl → full parse with correct structure', async () => {
    const result = await parseSession(path.join(FIXTURES, 'sample.jsonl'), 'test-session-001')
    expect(result.sessionId).toBe('test-session-001')
    // Title 來自 queue-operation 的 content（優先於 user 訊息）
    expect(result.title).toBe('Help me review code')
    expect(result.skippedLines).toBe(0)
    expect(result.totalLines).toBe(8)
    expect(result.messages.length).toBe(8)
    expect(result.startedAt).toBe('2024-06-01T10:00:00.000Z')
    expect(result.endedAt).toBe('2024-06-01T10:00:07.000Z')

    // 驗證 assistant with tool_use
    const assistantMsg = result.messages.find(m => m.uuid === 'a1')
    expect(assistantMsg).toBeDefined()
    expect(assistantMsg!.hasToolUse).toBe(true)
    expect(assistantMsg!.toolNames).toEqual(['Read'])
    expect(assistantMsg!.contentText).toBe("I'll review the code. Let me read it first.")

    // 驗證 assistant with multiple text blocks
    const assistant2 = result.messages.find(m => m.uuid === 'a2')
    expect(assistant2).toBeDefined()
    expect(assistant2!.contentText).toBe('The code looks clean.\nNo issues found.')
  })

  it('malformed.jsonl → skips bad line, continues', async () => {
    const result = await parseSession(path.join(FIXTURES, 'malformed.jsonl'), 'test-002')
    expect(result.skippedLines).toBe(1)
    expect(result.totalLines).toBe(3)
    expect(result.messages.length).toBe(2)
    expect(result.messages[0].type).toBe('user')
    expect(result.messages[1].type).toBe('assistant')
  })

  it('empty.jsonl → empty session', async () => {
    const result = await parseSession(path.join(FIXTURES, 'empty.jsonl'), 'empty-session')
    expect(result.messages).toEqual([])
    expect(result.totalLines).toBe(0)
    expect(result.title).toBe('empty-session')
  })

  it('title skips system-only messages and uses next real user message', async () => {
    const lines = [
      JSON.stringify({
        type: 'user',
        uuid: 'u1',
        timestamp: '2024-01-01T00:00:00.000Z',
        sessionId: 'xml-title',
        message: { role: 'user', content: '<ide_opened_file>User opened foo.ts.</ide_opened_file>' },
      }),
      JSON.stringify({
        type: 'user',
        uuid: 'u2',
        timestamp: '2024-01-01T00:00:01.000Z',
        sessionId: 'xml-title',
        message: { role: 'user', content: 'Fix the login bug' },
      }),
    ]
    const { writeFile, unlink } = await import('node:fs/promises')
    const { tmpdir } = await import('node:os')
    const tmpFile = path.join(tmpdir(), `test-xml-title-${Date.now()}.jsonl`)
    await writeFile(tmpFile, lines.join('\n'))
    try {
      const result = await parseSession(tmpFile, 'xml-title')
      expect(result.title).toBe('Fix the login bug')
    } finally {
      await unlink(tmpFile).catch(() => {})
    }
  })

  it('title truncated at 80 chars', async () => {
    // contentText 超過 80 字元時應截斷
    const longContent = 'A'.repeat(100)
    const line = JSON.stringify({
      type: 'user',
      uuid: 'u1',
      timestamp: '2024-01-01T00:00:00.000Z',
      sessionId: 'long-title',
      message: { role: 'user', content: longContent },
    })
    // 寫到臨時檔案
    const { writeFile } = await import('node:fs/promises')
    const { tmpdir } = await import('node:os')
    const tmpFile = path.join(tmpdir(), `test-long-title-${Date.now()}.jsonl`)
    await writeFile(tmpFile, line)

    const result = await parseSession(tmpFile, 'long-title')
    expect(result.title).toBe('A'.repeat(80) + '…')

    // cleanup
    const { unlink } = await import('node:fs/promises')
    await unlink(tmpFile)
  })
})
