import { describe, it, expect } from 'vitest'
import { mkdtemp, writeFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { ensureWellFormed, parseContent, parseLine, parseSession, stripSystemXml } from '../src/main/parser'
import { parseTaskFile } from '../src/main/task-parser'

const FIXTURES = path.join(__dirname, 'fixtures')

async function withTempTaskFile<T>(content: string, fn: (filePath: string) => Promise<T>): Promise<T> {
  const dir = await mkdtemp(path.join(tmpdir(), 'ccrewind-task-'))
  const filePath = path.join(dir, 'task.json')
  await writeFile(filePath, content)
  try {
    return await fn(filePath)
  } finally {
    await rm(dir, { recursive: true, force: true })
  }
}

describe('stripSystemXml', () => {
  // --- strip（完全移除標籤+內容）---

  it('removes <local-command-caveat> entirely', () => {
    const input = '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>'
    expect(stripSystemXml(input)).toBe('')
  })

  it('removes <task-notification> with nested tags', () => {
    const input = `<task-notification>
<task-id>bd93ty0eu</task-id>
<tool-use-id>toolu_016ZHSw5mPuUjNTWcv4RQbiy</tool-use-id>
<output-file>/private/tmp/claude-501/tasks/bd93ty0eu.output</output-file>
<status>completed</status>
<summary>Background command completed (exit code 0)</summary>
</task-notification>`
    expect(stripSystemXml(input)).toBe('')
  })

  it('removes <ide_opened_file> entirely', () => {
    const input = '<ide_opened_file>The user opened the file /Users/foo/bar.ts in the IDE. This may or may not be related to the current task.</ide_opened_file>'
    expect(stripSystemXml(input)).toBe('')
  })

  it('removes <system-reminder> entirely', () => {
    const input = '<system-reminder>Some system reminder text here.</system-reminder>'
    expect(stripSystemXml(input)).toBe('')
  })

  // --- unwrap（移除標籤，保留內容）---

  it('unwraps <command-name> keeping inner text', () => {
    const input = '<command-name>/gogo</command-name>'
    expect(stripSystemXml(input)).toBe('/gogo')
  })

  it('unwraps <command-message> keeping inner text', () => {
    const input = '<command-message>gogo</command-message>'
    expect(stripSystemXml(input)).toBe('gogo')
  })

  it('unwraps <command-args> keeping inner text', () => {
    const input = '<command-args>--verbose</command-args>'
    expect(stripSystemXml(input)).toBe('--verbose')
  })

  it('unwraps <local-command-stdout> keeping output text', () => {
    const input = '<local-command-stdout>Compacted </local-command-stdout>'
    expect(stripSystemXml(input)).toBe('Compacted')
  })

  // --- 混合場景 ---

  it('handles mixed system XML + user text', () => {
    const input = '<local-command-caveat>Caveat: DO NOT respond.</local-command-caveat>\nHello, please help me'
    expect(stripSystemXml(input)).toBe('Hello, please help me')
  })

  it('handles multiple system tags in one string', () => {
    const input = '<command-message>save-t</command-message>\n<command-name>/save-t</command-name>'
    expect(stripSystemXml(input)).toBe('save-t\n/save-t')
  })

  // --- 安全邊界 ---

  it('does NOT touch unknown XML tags (whitelist only)', () => {
    const input = '<custom-tag>user content</custom-tag>'
    expect(stripSystemXml(input)).toBe('<custom-tag>user content</custom-tag>')
  })

  it('does NOT touch HTML tags', () => {
    const input = '<div>some html</div>'
    expect(stripSystemXml(input)).toBe('<div>some html</div>')
  })

  it('returns empty string when only system XML remains', () => {
    const input = '<ide_opened_file>The user opened foo.ts in the IDE.</ide_opened_file>'
    expect(stripSystemXml(input)).toBe('')
  })

  it('trims surrounding whitespace after stripping', () => {
    const input = '  <local-command-caveat>Caveat text.</local-command-caveat>  \n  '
    expect(stripSystemXml(input)).toBe('')
  })

  it('handles empty string input', () => {
    expect(stripSystemXml('')).toBe('')
  })

  it('passes through plain text unchanged', () => {
    expect(stripSystemXml('Hello world')).toBe('Hello world')
  })
})

describe('parseContent', () => {
  it('string content → contentText directly', () => {
    const result = parseContent('Hello world')
    expect(result.contentText).toBe('Hello world')
    expect(result.hasToolUse).toBe(false)
    expect(result.hasToolResult).toBe(false)
    expect(result.toolNames).toEqual([])
  })

  it('null content → contentText null', () => {
    const result = parseContent(null)
    expect(result.contentText).toBeNull()
  })

  it('array with text blocks → concatenated with newline', () => {
    const content = [
      { type: 'text', text: 'Line 1' },
      { type: 'text', text: 'Line 2' },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('Line 1\nLine 2')
  })

  it('array with tool_use → marks flag and records name', () => {
    const content = [
      { type: 'text', text: 'Let me read it.' },
      { type: 'tool_use', id: 'toolu_001', name: 'Read', input: {} },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('Let me read it.')
    expect(result.hasToolUse).toBe(true)
    expect(result.toolNames).toEqual(['Read'])
  })

  it('array with tool_result → marks flag', () => {
    const content = [
      { type: 'tool_result', tool_use_id: 'toolu_001', content: 'file data' },
    ]
    const result = parseContent(content)
    expect(result.hasToolResult).toBe(true)
    expect(result.contentText).toBeNull()
  })

  it('array with tool_result is_error:true → toolErrorCount 1', () => {
    const content = [
      { type: 'tool_result', tool_use_id: 'toolu_001', content: 'Exit code 124', is_error: true },
    ]
    const result = parseContent(content)
    expect(result.toolErrorCount).toBe(1)
  })

  it('array with tool_result is_error:false → toolErrorCount 0 (false 是 91.4% 常態值)', () => {
    const content = [
      { type: 'tool_result', tool_use_id: 'toolu_001', content: 'ok', is_error: false },
    ]
    const result = parseContent(content)
    expect(result.toolErrorCount).toBe(0)
  })

  it('array with mixed is_error true/false/missing → toolErrorCount counts only === true', () => {
    const content = [
      { type: 'tool_result', tool_use_id: 'a', content: 'ok', is_error: false },
      { type: 'tool_result', tool_use_id: 'b', content: 'fail', is_error: true },
      { type: 'tool_result', tool_use_id: 'c', content: 'ok' },
      { type: 'tool_result', tool_use_id: 'd', content: 'truthy-but-not-true', is_error: 1 },
      { type: 'tool_result', tool_use_id: 'e', content: 'string-true', is_error: 'true' },
      { type: 'tool_result', tool_use_id: 'f', content: 'fail', is_error: true },
    ]
    const result = parseContent(content)
    // 嚴格 === true：跳過 missing / 0 / 1 / "true" 等 truthy/falsy 變體
    expect(result.toolErrorCount).toBe(2)
  })

  it('array with thinking → skipped, not in contentText', () => {
    const content = [
      { type: 'thinking', thinking: 'Let me think...' },
      { type: 'text', text: 'Here is the answer.' },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('Here is the answer.')
  })

  it('multiple tool_use → records all names', () => {
    const content = [
      { type: 'tool_use', id: 'toolu_001', name: 'Read', input: {} },
      { type: 'tool_use', id: 'toolu_002', name: 'Bash', input: {} },
    ]
    const result = parseContent(content)
    expect(result.toolNames).toEqual(['Read', 'Bash'])
  })

  it('strips system XML from string content', () => {
    const content = '<local-command-caveat>Caveat text.</local-command-caveat>'
    const result = parseContent(content)
    expect(result.contentText).toBeNull()
  })

  it('strips system XML from array text blocks', () => {
    const content = [
      { type: 'text', text: '<ide_opened_file>User opened foo.ts.</ide_opened_file>' },
      { type: 'text', text: 'Real user message here' },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('Real user message here')
  })

  it('unwraps command tags in array text blocks', () => {
    const content = [
      { type: 'text', text: '<command-message>gogo</command-message>\n<command-name>/gogo</command-name>' },
    ]
    const result = parseContent(content)
    expect(result.contentText).toBe('gogo\n/gogo')
  })

  it('flags isCommandWrapped when string content has command tag', () => {
    const result = parseContent('<command-name>/model</command-name>\n<command-message>model</command-message>')
    expect(result.isCommandWrapped).toBe(true)
  })

  it('flags isCommandWrapped when string content has local-command-stdout tag', () => {
    const result = parseContent('<local-command-stdout>Set model to Opus 4.7</local-command-stdout>')
    expect(result.isCommandWrapped).toBe(true)
  })

  it('flags isCommandWrapped when array text block has command tag', () => {
    const content = [
      { type: 'text', text: '<command-name>/gogo</command-name>' },
    ]
    const result = parseContent(content)
    expect(result.isCommandWrapped).toBe(true)
  })

  it('does NOT flag isCommandWrapped for plain user text', () => {
    expect(parseContent('Hello world').isCommandWrapped).toBe(false)
    expect(parseContent([{ type: 'text', text: 'normal message' }]).isCommandWrapped).toBe(false)
  })

  it('replaces lone high surrogate in string content with U+FFFD', () => {
    const result = parseContent('pre\uD83Dpost')
    expect(result.contentText).toBe('pre�post')
  })

  it('replaces lone low surrogate in array text block with U+FFFD', () => {
    const content = [{ type: 'text', text: 'pre\uDC36post' }]
    const result = parseContent(content)
    expect(result.contentText).toBe('pre�post')
  })

  it('preserves valid surrogate pair (emoji) untouched', () => {
    const result = parseContent('hello 🐶 world')
    expect(result.contentText).toBe('hello 🐶 world')
  })
})

describe('ensureWellFormed', () => {
  it('passes through plain ASCII unchanged', () => {
    expect(ensureWellFormed('hello world')).toBe('hello world')
  })

  it('passes through valid surrogate pair (emoji) unchanged', () => {
    expect(ensureWellFormed('🚀')).toBe('🚀')
  })

  it('replaces lone high surrogate with U+FFFD', () => {
    expect(ensureWellFormed('a\uD83Db')).toBe('a�b')
  })

  it('replaces lone low surrogate with U+FFFD', () => {
    expect(ensureWellFormed('a\uDC36b')).toBe('a�b')
  })
})

describe('parseLine', () => {
  it('user message with string content', () => {
    const line = JSON.stringify({
      type: 'user',
      uuid: 'u1',
      parentUuid: null,
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 'sess-001',
      message: { role: 'user', content: 'Hello' },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('user')
    expect(result!.role).toBe('user')
    expect(result!.contentText).toBe('Hello')
    expect(result!.uuid).toBe('u1')
    expect(result!.timestamp).toBe('2024-06-01T10:00:00.000Z')
  })

  it('assistant message with tool_use', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a1',
      parentUuid: 'u1',
      timestamp: '2024-06-01T10:00:01.000Z',
      sessionId: 'sess-001',
      message: {
        role: 'assistant',
        content: [
          { type: 'text', text: 'Reading file.' },
          { type: 'tool_use', id: 'toolu_001', name: 'Read', input: {} },
        ],
      },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.role).toBe('assistant')
    expect(result!.contentText).toBe('Reading file.')
    expect(result!.hasToolUse).toBe(true)
    expect(result!.toolNames).toEqual(['Read'])
  })

  it('malformed JSON → returns null', () => {
    expect(parseLine('NOT VALID JSON')).toBeNull()
    expect(parseLine('{{{broken')).toBeNull()
  })

  it('empty line → returns null', () => {
    expect(parseLine('')).toBeNull()
    expect(parseLine('  ')).toBeNull()
  })

  it('unknown type → still returns ParsedLine', () => {
    const line = JSON.stringify({ type: 'file-history-snapshot', sessionId: 's1' })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('file-history-snapshot')
    expect(result!.contentText).toBeNull()
  })

  it('queue-operation top-level content normalizes lone surrogate', () => {
    const line = JSON.stringify({
      type: 'queue-operation',
      sessionId: 's1',
      content: 'pre\uD83Dpost',
    })
    const result = parseLine(line)
    expect(result!.contentText).toBe('pre�post')
  })

  it('contentJson is well-formed after JSON.parse round-trip', () => {
    const line = JSON.stringify({
      type: 'user',
      sessionId: 's1',
      message: {
        role: 'user',
        content: [
          { type: 'tool_result', tool_use_id: 't1', content: 'pre\uD83Dpost' },
        ],
      },
    })
    const result = parseLine(line)
    expect(result!.contentJson).not.toBeNull()
    const restored = JSON.parse(result!.contentJson!)
    expect(restored[0].content).toBe('pre�post')
  })

  it('queue-operation with content → extracts prompt text', () => {
    const line = JSON.stringify({
      type: 'queue-operation',
      operation: 'enqueue',
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 's1',
      content: 'Help me debug this',
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('queue-operation')
    expect(result!.role).toBeNull()
    expect(result!.contentText).toBe('Help me debug this')
  })

  it('queue-operation without content → contentText null', () => {
    const line = JSON.stringify({
      type: 'queue-operation',
      operation: 'dequeue',
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 's1',
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.contentText).toBeNull()
  })

  it('extracts requestId from top-level field', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a1',
      requestId: 'req_011CZVkxXRnVB3AAiJXkgBUm',
      timestamp: '2024-06-01T10:00:01.000Z',
      sessionId: 'sess-001',
      message: { role: 'assistant', content: [{ type: 'text', text: 'Hello' }] },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.requestId).toBe('req_011CZVkxXRnVB3AAiJXkgBUm')
  })

  it('requestId is null when field is missing', () => {
    const line = JSON.stringify({
      type: 'user',
      uuid: 'u1',
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 's1',
      message: { role: 'user', content: 'Hello' },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.requestId).toBeNull()
  })

  it('requestId is null when field is not a string', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a1',
      requestId: 12345,
      timestamp: '2024-06-01T10:00:01.000Z',
      sessionId: 'sess-001',
      message: { role: 'assistant', content: [{ type: 'text', text: 'Hi' }] },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.requestId).toBeNull()
  })
})

describe('parseLine rawJson preservation (parseFailed fallback)', () => {
  it('known type (user) → rawJson is null', () => {
    const line = JSON.stringify({
      type: 'user',
      uuid: 'u1',
      timestamp: '2024-06-01T10:00:00.000Z',
      sessionId: 's1',
      message: { role: 'user', content: 'Hello' },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.rawJson).toBeNull()
  })

  it('known type (file-history-snapshot) → rawJson is null', () => {
    const line = JSON.stringify({ type: 'file-history-snapshot', sessionId: 's1' })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.rawJson).toBeNull()
  })

  it('unknown type → rawJson preserves entire original line (debug fallback)', () => {
    const line = JSON.stringify({
      type: 'reasoning-trace',
      sessionId: 's1',
      payload: { steps: ['a', 'b'] },
    })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('reasoning-trace')
    expect(result!.rawJson).toBe(line)
  })

  it('missing type field → rawJson preserved (parser cannot classify)', () => {
    const line = JSON.stringify({ sessionId: 's1', message: 'no type field' })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.type).toBe('unknown')
    expect(result!.rawJson).toBe(line)
  })

  it('non-string type field → rawJson preserved', () => {
    const line = JSON.stringify({ type: 42, sessionId: 's1' })
    const result = parseLine(line)
    expect(result).not.toBeNull()
    expect(result!.rawJson).toBe(line)
  })
})

describe('parseSession', () => {
  it('sample.jsonl → full parse with correct structure', async () => {
    const result = await parseSession(path.join(FIXTURES, 'sample.jsonl'), 'test-session-001')
    expect(result.sessionId).toBe('test-session-001')
    // Title 來自 queue-operation 的 content（優先於 user 訊息）
    expect(result.title).toBe('Help me review code')
    expect(result.skippedLines).toBe(0)
    expect(result.totalLines).toBe(8)
    expect(result.messages.length).toBe(8)
    expect(result.startedAt).toBe('2024-06-01T10:00:00.000Z')
    expect(result.endedAt).toBe('2024-06-01T10:00:07.000Z')

    // 驗證 assistant with tool_use
    const assistantMsg = result.messages.find(m => m.uuid === 'a1')
    expect(assistantMsg).toBeDefined()
    expect(assistantMsg!.hasToolUse).toBe(true)
    expect(assistantMsg!.toolNames).toEqual(['Read'])
    expect(assistantMsg!.contentText).toBe("I'll review the code. Let me read it first.")

    // 驗證 assistant with multiple text blocks
    const assistant2 = result.messages.find(m => m.uuid === 'a2')
    expect(assistant2).toBeDefined()
    expect(assistant2!.contentText).toBe('The code looks clean.\nNo issues found.')
  })

  it('malformed.jsonl → skips bad line, continues', async () => {
    const result = await parseSession(path.join(FIXTURES, 'malformed.jsonl'), 'test-002')
    expect(result.skippedLines).toBe(1)
    expect(result.totalLines).toBe(3)
    expect(result.messages.length).toBe(2)
    expect(result.messages[0].type).toBe('user')
    expect(result.messages[1].type).toBe('assistant')
  })

  it('empty.jsonl → empty session', async () => {
    const result = await parseSession(path.join(FIXTURES, 'empty.jsonl'), 'empty-session')
    expect(result.messages).toEqual([])
    expect(result.totalLines).toBe(0)
    expect(result.title).toBe('empty-session')
  })

  it('title skips system-only messages and uses next real user message', async () => {
    const lines = [
      JSON.stringify({
        type: 'user',
        uuid: 'u1',
        timestamp: '2024-01-01T00:00:00.000Z',
        sessionId: 'xml-title',
        message: { role: 'user', content: '<ide_opened_file>User opened foo.ts.</ide_opened_file>' },
      }),
      JSON.stringify({
        type: 'user',
        uuid: 'u2',
        timestamp: '2024-01-01T00:00:01.000Z',
        sessionId: 'xml-title',
        message: { role: 'user', content: 'Fix the login bug' },
      }),
    ]
    const { writeFile, unlink } = await import('node:fs/promises')
    const { tmpdir } = await import('node:os')
    const tmpFile = path.join(tmpdir(), `test-xml-title-${Date.now()}.jsonl`)
    await writeFile(tmpFile, lines.join('\n'))
    try {
      const result = await parseSession(tmpFile, 'xml-title')
      expect(result.title).toBe('Fix the login bug')
    } finally {
      await unlink(tmpFile).catch(() => {})
    }
  })

  it('title truncated at 80 chars', async () => {
    // contentText 超過 80 字元時應截斷
    const longContent = 'A'.repeat(100)
    const line = JSON.stringify({
      type: 'user',
      uuid: 'u1',
      timestamp: '2024-01-01T00:00:00.000Z',
      sessionId: 'long-title',
      message: { role: 'user', content: longContent },
    })
    // 寫到臨時檔案
    const { writeFile } = await import('node:fs/promises')
    const { tmpdir } = await import('node:os')
    const tmpFile = path.join(tmpdir(), `test-long-title-${Date.now()}.jsonl`)
    await writeFile(tmpFile, line)

    const result = await parseSession(tmpFile, 'long-title')
    expect(result.title).toBe('A'.repeat(80) + '…')

    // cleanup
    const { unlink } = await import('node:fs/promises')
    await unlink(tmpFile)
  })
})

describe('parseTaskFile', () => {
  it('valid completed task → parsed', async () => {
    const content = JSON.stringify({
      id: '7',
      subject: 'Add SPDX headers to all TS files',
      description: 'src/**/*.ts and tests/**/*.ts add SPDX header',
      activeForm: 'Adding SPDX headers',
      status: 'completed',
      blocks: [],
      blockedBy: [],
    })
    const result = await withTempTaskFile(content, parseTaskFile)
    expect(result).not.toBeNull()
    expect(result!.id).toBe('7')
    expect(result!.subject).toBe('Add SPDX headers to all TS files')
    expect(result!.status).toBe('completed')
    expect(result!.blocks).toEqual([])
    expect(result!.blockedBy).toEqual([])
  })

  it('valid pending task with blockedBy → parsed', async () => {
    const content = JSON.stringify({
      id: '2',
      subject: 'Run migration',
      description: null,
      activeForm: 'Running migration',
      status: 'pending',
      blocks: ['3'],
      blockedBy: ['1'],
    })
    const result = await withTempTaskFile(content, parseTaskFile)
    expect(result!.id).toBe('2')
    expect(result!.status).toBe('pending')
    expect(result!.description).toBeNull()
    expect(result!.blocks).toEqual(['3'])
    expect(result!.blockedBy).toEqual(['1'])
  })

  it('missing required field id → null', async () => {
    const content = JSON.stringify({
      subject: 'No id',
      status: 'pending',
    })
    const result = await withTempTaskFile(content, parseTaskFile)
    expect(result).toBeNull()
  })

  it('missing required field subject → null', async () => {
    const content = JSON.stringify({
      id: '1',
      status: 'pending',
    })
    const result = await withTempTaskFile(content, parseTaskFile)
    expect(result).toBeNull()
  })

  it('missing required field status → null', async () => {
    const content = JSON.stringify({
      id: '1',
      subject: 'No status',
    })
    const result = await withTempTaskFile(content, parseTaskFile)
    expect(result).toBeNull()
  })

  it('malformed JSON → null', async () => {
    const result = await withTempTaskFile('{not valid json', parseTaskFile)
    expect(result).toBeNull()
  })

  it('top-level array → null', async () => {
    const result = await withTempTaskFile('[]', parseTaskFile)
    expect(result).toBeNull()
  })

  it('unknown status enum → preserved as raw string', async () => {
    // 未來 Claude Code 新增 status (e.g. 'cancelled') 時，parser 保留原值，UI 層 fallback 顯示
    const content = JSON.stringify({
      id: '1',
      subject: 'Future status',
      status: 'cancelled',
    })
    const result = await withTempTaskFile(content, parseTaskFile)
    expect(result!.status).toBe('cancelled')
  })

  it('non-array blocks → coerced to empty array', async () => {
    const content = JSON.stringify({
      id: '1',
      subject: 'Coerce',
      status: 'pending',
      blocks: 'not-an-array',
      blockedBy: null,
    })
    const result = await withTempTaskFile(content, parseTaskFile)
    expect(result!.blocks).toEqual([])
    expect(result!.blockedBy).toEqual([])
  })

  it('non-string element in blocks → filtered out', async () => {
    const content = JSON.stringify({
      id: '1',
      subject: 'Filter',
      status: 'pending',
      blocks: ['2', 3, null, '4'],
      blockedBy: [],
    })
    const result = await withTempTaskFile(content, parseTaskFile)
    expect(result!.blocks).toEqual(['2', '4'])
  })

  it('missing file → null', async () => {
    const result = await parseTaskFile('/tmp/does-not-exist-ccrewind-task.json')
    expect(result).toBeNull()
  })
})

// ── v21 schema: image / attribution / api_error / edited_text_file ──

describe('parseContent — image block', () => {
  it('detects image block and sets hasImage', () => {
    const content = [
      { type: 'text', text: 'Here is the screenshot' },
      { type: 'image', source: { type: 'base64', media_type: 'image/png', data: 'iVBOR...' } },
    ]
    const result = parseContent(content)
    expect(result.hasImage).toBe(true)
    expect(result.contentText).toBe('Here is the screenshot')
  })

  it('hasImage false when no image block', () => {
    const content = [{ type: 'text', text: 'No images here' }]
    const result = parseContent(content)
    expect(result.hasImage).toBe(false)
  })

  it('hasImage false for string content', () => {
    const result = parseContent('Just a string')
    expect(result.hasImage).toBe(false)
  })

  it('hasImage false for null content', () => {
    const result = parseContent(null)
    expect(result.hasImage).toBe(false)
  })
})

describe('parseLine — base64 image stripping in contentJson', () => {
  it('strips base64 data from image blocks in contentJson', () => {
    const line = JSON.stringify({
      type: 'user',
      uuid: 'img-1',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      message: {
        role: 'user',
        content: [
          { type: 'text', text: 'Look at this' },
          { type: 'image', source: { type: 'base64', media_type: 'image/png', data: 'A'.repeat(1000) } },
        ],
      },
    })
    const result = parseLine(line)!
    expect(result.hasImage).toBe(true)
    const parsed = JSON.parse(result.contentJson!)
    expect(parsed[1].type).toBe('image')
    expect(parsed[1].source.type).toBe('base64')
    expect(parsed[1].source.media_type).toBe('image/png')
    expect(parsed[1].source.data).toBe('[base64-stripped]')
  })

  it('preserves non-base64 image source intact', () => {
    const line = JSON.stringify({
      type: 'user',
      uuid: 'img-2',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      message: {
        role: 'user',
        content: [
          { type: 'image', source: { type: 'url', url: 'https://example.com/img.png' } },
        ],
      },
    })
    const result = parseLine(line)!
    expect(result.hasImage).toBe(true)
    const parsed = JSON.parse(result.contentJson!)
    expect(parsed[0].source.url).toBe('https://example.com/img.png')
  })

  it('does not strip tool_result content even if long', () => {
    const longContent = 'x'.repeat(2000)
    const line = JSON.stringify({
      type: 'user',
      uuid: 'tr-1',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      message: {
        role: 'user',
        content: [
          { type: 'tool_result', tool_use_id: 't1', content: longContent },
        ],
      },
    })
    const result = parseLine(line)!
    expect(result.hasImage).toBe(false)
    const parsed = JSON.parse(result.contentJson!)
    expect(parsed[0].content).toBe(longContent)
  })
})

describe('parseLine — attribution fields', () => {
  it('extracts attributionSkill from assistant entry', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a1',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      attributionSkill: 'save-t',
      message: { role: 'assistant', content: 'Done' },
    })
    const result = parseLine(line)!
    expect(result.attributionSkill).toBe('save-t')
    expect(result.attributionPlugin).toBeNull()
    expect(result.attributionMcpServer).toBeNull()
    expect(result.attributionMcpTool).toBeNull()
    expect(result.attributionAgent).toBeNull()
  })

  it('extracts attributionMcpServer and attributionMcpTool', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a2',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      attributionMcpServer: 'context7',
      attributionMcpTool: 'query-docs',
      message: { role: 'assistant', content: 'Found docs' },
    })
    const result = parseLine(line)!
    expect(result.attributionMcpServer).toBe('context7')
    expect(result.attributionMcpTool).toBe('query-docs')
  })

  it('attributionAgent from subagent entry', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a3',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      attributionAgent: 'Explore',
      message: { role: 'assistant', content: 'Searched' },
    })
    const result = parseLine(line)!
    expect(result.attributionAgent).toBe('Explore')
  })

  it('non-string attribution values are ignored', () => {
    const line = JSON.stringify({
      type: 'assistant',
      uuid: 'a4',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      attributionSkill: 42,
      message: { role: 'assistant', content: 'Bad' },
    })
    const result = parseLine(line)!
    expect(result.attributionSkill).toBeNull()
  })
})

describe('parseLine — system subtype and api_error', () => {
  it('extracts system subtype', () => {
    const line = JSON.stringify({
      type: 'system',
      uuid: 'sys-1',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      subtype: 'turn_duration',
      durationMs: 5000,
      content: '',
    })
    const result = parseLine(line)!
    expect(result.systemSubtype).toBe('turn_duration')
    expect(result.apiErrorStatus).toBeNull()
  })

  it('extracts api_error status', () => {
    const line = JSON.stringify({
      type: 'system',
      uuid: 'sys-2',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      subtype: 'api_error',
      error: { status: 529, type: 'overloaded_error', error: { type: 'overloaded_error', message: 'Overloaded' } },
      content: '',
    })
    const result = parseLine(line)!
    expect(result.systemSubtype).toBe('api_error')
    expect(result.apiErrorStatus).toBe(529)
  })

  it('api_error with missing error object → null status', () => {
    const line = JSON.stringify({
      type: 'system',
      uuid: 'sys-3',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      subtype: 'api_error',
      content: '',
    })
    const result = parseLine(line)!
    expect(result.systemSubtype).toBe('api_error')
    expect(result.apiErrorStatus).toBeNull()
  })

  it('non-system type → systemSubtype null', () => {
    const line = JSON.stringify({
      type: 'user',
      uuid: 'u-1',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      subtype: 'should-be-ignored',
      message: { role: 'user', content: 'Hi' },
    })
    const result = parseLine(line)!
    expect(result.systemSubtype).toBeNull()
  })
})

describe('parseLine — edited_text_file attachment', () => {
  it('extracts filename from edited_text_file attachment', () => {
    const line = JSON.stringify({
      type: 'attachment',
      uuid: 'att-1',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      attachment: {
        type: 'edited_text_file',
        filename: '/Users/dev/project/src/app.tsx',
        snippet: '1\timport React from "react"',
      },
    })
    const result = parseLine(line)!
    expect(result.editedFilePath).toBe('/Users/dev/project/src/app.tsx')
  })

  it('non-edited_text_file attachment → editedFilePath null', () => {
    const line = JSON.stringify({
      type: 'attachment',
      uuid: 'att-2',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
      attachment: { type: 'hook_success', hookName: 'start', content: 'ok' },
    })
    const result = parseLine(line)!
    expect(result.editedFilePath).toBeNull()
  })

  it('missing attachment object → editedFilePath null', () => {
    const line = JSON.stringify({
      type: 'attachment',
      uuid: 'att-3',
      sessionId: 's1',
      timestamp: '2026-06-07T00:00:00Z',
    })
    const result = parseLine(line)!
    expect(result.editedFilePath).toBeNull()
  })
})
